### ISSUE TITLE
adf install (falha)

### ISSUE THREAD

**Issue by kyriosdata** [mrodriguesfilho/adf-cli#12]
fabio@s130:~/Downloads$ ./adf install
Baixando a JVM versão: 21.0.3 100% [==============] (50/50 MB, 28 MB/s)        
Baixando o HAPIFHIR versão: 7.0.2 100% [=======] (295/295 MB, 16 MB/s)         
2024/07/25 17:09:04 Get "": unsupported protocol scheme ""
2024/07/25 17:09:04 Get "": unsupported protocol scheme ""
Não foi possível fazer a instalação HapiFhirValidator. Erro: Get "": unsupported protocol scheme ""

**Comment by mrodriguesfilho** [comment]
@kyriosdata 

Pode colocar a cópia do preferences.json para eu validar? 

Ontem enquanto ajustava a documentação, eu testei os comandos novamente, estavam todos funcionais.

**Comment by kyriosdata** [comment]
@mrodriguesfilho segue o arquivo
[preferences.json](https://github.com/user-attachments/files/16384023/preferences.json)

**Comment by mrodriguesfilho** [comment]
@kyriosdata 

Causa raiz: arquivo do preferences.json antigo não tem a url do serviço do hapfhir validator

Para sanar esse gap, no final de semana vou adicionar um feature novo que consulta a ultima versão do json com os serviços, se a versão local do usuário for inferior a ultima ( assumindo que ele não especificou a versão que ele queria usar ), fazemos o download da mais recente.

**Comment by mrodriguesfilho** [comment]
@kyriosdata 

Release 0.7.0 adiciona uma validação de versão do preferences.json

Dessa forma, quando fizermos uma alteração incluindo novos serviços ou mudando a url, os usuários que tiverem com uma versão incompatível ( o caso da sua máquina ), vão fazer o download da ultima versão sobrescrevendo a versão antiga
