### ISSUE TITLE
Release 0.0.3

### ISSUE THREAD

**Issue by kyriosdata** [mrodriguesfilho/adf-cli#4]
Observação: alguns itens já discutidos no corpo da issue #1 continuam válidos e precisam ser considerados, como o uso do diretório .adf e outros. 

Resultados esperados:

- diretório local do adf é criado quando executado, se já não está disponível (**.adf**).
- implementar comando **list** que exibe as versões disponíveis dos "serviços". A lista de versões deve vir de um arquivo json, disponibilizado no Github, **releases**, à semelhança das versões do próprio adf. Ou seja, além dos próprios executáveis agora estará disponível um arquivo, por exemplo, versoes.json, a ser consultado pelo adf quando o comando list for executado. Por ora, apenas exibir a lista (_semantic versioning_) dos serviços é suficiente. 
- Observe que se o adf não tiver acesso à internet, então não será possível obter a lista "atualizada". Uma opção é esclarecer este cenário ao usuário e informar que a lista que segue é interna, não necessariamente a mais recente.

**Comment by mrodriguesfilho** [comment]
@kyriosdata a versão 0.1.0 atende alguns comentários feitos.

- O arquivo preferences.json é criado na primeira vez que o cli roda na pasta .adf
- Built-in à aplicação temos uma lista com as urls de download, então caso não haja conexão com a internet, agora ele usa a lista local para criar o arquivo preferences
- Fez se necessário criar um novo comando de update para atualizar o preferences. Seguindo a ideia de package managers UNIX. Para atualizar as versões dos pacotes, é necessário, por exemplo, apt-get update, no linux.

**Comment by kyriosdata** [comment]
@mrodriguesfilho perfeito, progresso realizado.
