### ISSUE TITLE
Release 0.1.0

### ISSUE THREAD

**Issue by kyriosdata** [mrodriguesfilho/adf-cli#5]
- Vamos obter as JVMs do repositório contendo releases tanto para windows, quanto para Mac e Linux: https://github.com/adoptium/temurin21-binaries/releases. Por exemplo, o link https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.3%2B9/OpenJDK21U-jre_x64_linux_hotspot_21.0.3_9.tar.gz é um link possível. 
- Atualizar o arquivo **serviceData.json** para conter esta mesma versão (21.0.3) para as três plataformas oferecidas. Neste caso, teremos três valores para downloadUrl, um para cada plataforma. A estrutura de serviceData terá que ser alterada para acomodar a plataforma (win, mac, linux). 
- O formato do arquivo é algo como OpenJDK21U-jre_x64_<so>_hotspot_<versao>.tar.gz. Ou seja, estaremos baixando a versão .tar.gz. O <so> será definido pelo próprio aplicativo. Se o adf estiver executando no linux será linux, se windows, será windows, se no mac, então será mac. Também observe que estamos usando o jre (não é o jdk). 
- Ao requisitar a instalação de uma dada versão (não será possível escolher a plataforma), o conteúdo de downloadUrl será consultado para recuperar a URL a ser utilizada para baixar o arquivo. Após recuperado, deverá ser descomprimido. O diretório gerado deve ser movido para algum lugar em **.adf**.

**Comment by mrodriguesfilho** [comment]
@kyriosdata feito o release da versão 0.1.0

Alguns pontos levantados nessa release:

- A criação do arqiuvo preferences.json é feita na pasta .adf somente a primeira vez que o cli é executado. Sendo necessária a criação de um comando update (incluir na próxima issue) para atualizar a lista de serviços. Por hora a lista contem apenas os JREs do github especificado
- O requisito e uma issue anterior que, quando finalizar o download e descompressão da JRE ser feita uma chamada java -version tornou-se instável. Ao descomprimir os arquivos, as pastas nas quais as jres estão variam de acordo com OS e a versão do JRE propriamente. Faz sentido descomprimir na raiz da pasta /jvm/version/, visto que já haviamos criado um feature que separava cada JRE por pasta versionada?

**Comment by kyriosdata** [comment]
@mrodriguesfilho feito.
