### ISSUE TITLE
Erro ao iniciar (adf start)

### ISSUE THREAD

**Issue by kyriosdata** [mrodriguesfilho/adf-cli#9]
Conforme a mensagem abaixo, ao fazer uso da variável de ambiente ADF_HOME, obtém-se o seguinte cenário:

![image](https://github.com/mrodriguesfilho/adf-cli/assets/1735792/1d0962b6-bd3b-4ade-b69c-cf632da9be74)

**Comment by mrodriguesfilho** [comment]
@kyriosdata 

O bug foi gerado a partir do momento em que adicionamos a versão do bundle na aplicação. Correção foi feita e está disponível na versão 0.6.0.
